In [62]:
import pandas as pd
import numpy as np
import os
import sys

In [63]:
a = np.arange(15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
a.shape

(15,)

In [67]:
a.resize()

In [68]:
a.ndim

1

In [69]:
a.size

15

In [70]:
u = np.eye(5)
u

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
ls = [[1,2,3,4,5],[6,7,8,9,10]]
np.array(ls)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [85]:
np.zeros(5)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
b = np.random.random((3,3))

In [92]:
b

array([[0.64425182, 0.54481782, 0.74146632],
       [0.79937841, 0.07059548, 0.95873866],
       [0.21425567, 0.87714411, 0.37436454]])

In [93]:
b * 4

array([[2.5770073 , 2.17927127, 2.96586528],
       [3.19751364, 0.28238192, 3.83495463],
       [0.85702269, 3.50857645, 1.49745817]])

In [9]:
#if b < 1 returns 1 othweise retruns b(the array)
c = np.where(b < 1,1,b)
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
n = pd.Series({'A': 1,'B':2})
n

A    1
B    2
dtype: int64

In [96]:
#converts Series to Dataframe
n.to_frame()

0
A  1
B  2

In [100]:
dic = {
    'city':['Nante','joigny','Paris','Nice'],
    'state':['Nante','Bourgogne','Ils de France','Nice'],
    'id':[5,6,7,8]
}
df1 = pd.DataFrame(dic,columns=['city','state','id']) 

In [101]:
# this first index city and second index state and 
#and do not drop city and state columns leave them
df1.set_index(['city', 'state'], drop=False) 

city          state  id
city   state                                   
Nante  Nante           Nante          Nante   5
joigny Bourgogne      joigny      Bourgogne   6
Paris  Ils de France   Paris  Ils de France   7
Nice   Nice             Nice           Nice   8

In [103]:
dic2 = {
    'city':['nante','joigny','paris','nice'],
    'address':['five','six','seven','eight'],
    'id':[5,6,7,8]
}
df2 = pd.DataFrame(dic2,columns=['city','address','id']) 

In [104]:
# concatinate== joins tow df along with columns:we have col displayed
new_df = pd.concat([df1,df2],axis=1)
new_df

city          state  id    city address  id
0   Nante          Nante   5   nante    five   5
1  joigny      Bourgogne   6  joigny     six   6
2   Paris  Ils de France   7   paris   seven   7
3    Nice           Nice   8    nice   eight   8

In [105]:
#merge
d = pd.merge(df1,df2,how='outer',indicator=True)
d

city          state  id address      _merge
0   Nante          Nante   5     NaN   left_only
1  joigny      Bourgogne   6     six        both
2   Paris  Ils de France   7     NaN   left_only
3    Nice           Nice   8     NaN   left_only
4   nante            NaN   5    five  right_only
5   paris            NaN   7   seven  right_only
6    nice            NaN   8   eight  right_only

In [107]:
#pivot table
dict = {
    'city': ['rome','sinar','sidney','london','rome','sinar','sidney'],
    'rank':['one','two','one','two','one','two','one'],
    'score1':[22,45,55,66,40,30,20],
    'score2':[80,70,60,50,40,30,20]
       }
d = pd.DataFrame(dict,columns=['city','rank','score1','score2'])

In [108]:
d

city rank  score1  score2
0    rome  one      22      80
1   sinar  two      45      70
2  sidney  one      55      60
3  london  two      66      50
4    rome  one      40      40
5   sinar  two      30      30
6  sidney  one      20      20

In [21]:
pivot = pd.pivot_table(d, index=['city','rank'],aggfunc='count')

In [109]:
pivot

score1  score2
city   rank                
london two        1       1
rome   one        2       2
sidney one        2       2
sinar  two        2       2

In [110]:
f = pd.pivot_table(d,index='city',aggfunc='sum')
f

score1  score2
city                  
london      66      50
rome        62     120
sidney      75      80
sinar       75     100

In [111]:
pivot.duplicated().sum()

2

In [112]:
#duplicated, it tells where col or rows are repeated
# d.duplicated() # by default it displays the rows 
d.duplicated(['city'])

0    False
1    False
2    False
3    False
4     True
5     True
6     True
dtype: bool

In [113]:
# to drop duplicated values 
d.drop_duplicates(['city','rank'])

city rank  score1  score2
0    rome  one      22      80
1   sinar  two      45      70
2  sidney  one      55      60
3  london  two      66      50

In [114]:
#we can add columns using MAP func 
#if we want to add other countries names to city columns
country = {'Italy':'Napoli','Sudan':'hajabdallah','Australia':'toronto','UK':'wils'}

In [115]:
d['city'].map(country)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
Name: city, dtype: object

In [116]:
 # this adds new col along with it values 
d['country'] = d['city'].map(country)

In [30]:
#groupby it gives us more info about specific things

In [117]:
d['score1'].groupby(d['city']).describe()

count  mean        std   min    25%   50%    75%   max
city                                                          
london    1.0  66.0        NaN  66.0  66.00  66.0  66.00  66.0
rome      2.0  31.0  12.727922  22.0  26.50  31.0  35.50  40.0
sidney    2.0  37.5  24.748737  20.0  28.75  37.5  46.25  55.0
sinar     2.0  37.5  10.606602  30.0  33.75  37.5  41.25  45.0

In [119]:
#appy
# d.groupby('city').apply(lambda x: (np.log2(x['score1'])))
d.groupby('city').apply(lambda x: np.mean(np.log2(x['score1'])))

city
london    6.044394
rome      4.890680
sidney    5.051644
sinar     5.199372
dtype: float64

In [120]:
d.describe()

score1     score2
count   7.000000   7.000000
mean   39.714286  50.000000
std    17.075463  21.602469
min    20.000000  20.000000
25%    26.000000  35.000000
50%    40.000000  50.000000
75%    50.000000  65.000000
max    66.000000  80.000000

In [34]:
#aggration it aggregates and outputs it in one col.
d.agg('count') 

city       7
rank       7
score1     7
score2     7
country    0
dtype: int64

In [121]:
# #bining, when using bining we use cut with pandas
bins = [0,25,50,75,100]
label_names = ['low','average','good','brilliant']
d['grade'] = pd.cut(d['score2'], bins, labels =label_names)
d

city rank  score1  score2 country      grade
0    rome  one      22      80     NaN  brilliant
1   sinar  two      45      70     NaN       good
2  sidney  one      55      60     NaN       good
3  london  two      66      50     NaN    average
4    rome  one      40      40     NaN    average
5   sinar  two      30      30     NaN    average
6  sidney  one      20      20     NaN        low

In [125]:
#using reindex we can change the index of the rows and col
#for the row
v = d.reindex([0,1,2,3,4,5,6])
v

city rank  score1  score2 country      grade
0    rome  one      22      80     NaN  brilliant
1   sinar  two      45      70     NaN       good
2  sidney  one      55      60     NaN       good
3  london  two      66      50     NaN    average
4    rome  one      40      40     NaN    average
5   sinar  two      30      30     NaN    average
6  sidney  one      20      20     NaN        low

In [127]:
col_names1 = ['city','rank','score1','score2','country']
n = d.reindex(columns = col_names1)
n

city rank  score1  score2 country
0    rome  one      22      80     NaN
1   sinar  two      45      70     NaN
2  sidney  one      55      60     NaN
3  london  two      66      50     NaN
4    rome  one      40      40     NaN
5   sinar  two      30      30     NaN
6  sidney  one      20      20     NaN

In [129]:
#replacing value
d['city'].replace(['rome','Napoli'],inplace=True)
#for several cols
d['city'].replace(['Madani','sinar'],['M','Rome'],inplace=True)

In [130]:
d

city rank  score1  score2 country      grade
0    rome  one      22      80     NaN  brilliant
1    Rome  two      45      70     NaN       good
2  sidney  one      55      60     NaN       good
3  london  two      66      50     NaN    average
4  london  one      40      40     NaN    average
5    Rome  two      30      30     NaN    average
6  sidney  one      20      20     NaN        low

In [43]:
# we can use iat and at to change index name
#iat for index integer
#at for labels integer
# d.iloc[2][0]
#we can use iat to change index name 
# d.iat[0,0]
d.iat[0,0]= 'madani'

In [44]:
# d.set_index('city',inplace=True)

In [131]:
#using at 
d.at['madani','country'] = 'Kosti'

In [132]:
d['score1'].rank(ascending=False)

0         6.0
1         3.0
2         2.0
3         1.0
4         4.0
5         5.0
6         7.0
madani    NaN
Name: score1, dtype: float64

In [133]:
#how to know the number of rows and cols
# d.shape #this gives us number of rows and cols
# nrow = d.shape[0] # gives nrows
ncol = d.shape[1] # gives ncols

In [134]:
ncol

6

In [49]:
    #counts number of time of each unique value appears in a certain column
pd.value_counts(d['score2'])

20.0    1
30.0    1
40.0    1
50.0    1
60.0    1
70.0    1
80.0    1
Name: score2, dtype: int64

pd.value_counts(d.city)
df.city.value_counts()
pd.value_counts(df)
df.apply(pd.value_counts)

In [135]:
#to count the values for entire dataframe we use apply method
#     d.apply(pd.value_counts)
d.apply(pd.value_counts).fillna(0) # to fill the empty espace with 0 so that it looks nice 

C:\Users\Raed\Anaconda3\lib\site-packages\pandas\core\indexes\api.py:107: RuntimeWarning: '<' not supported between instances of 'str' and 'float', sort order is undefined for incomparable objects
  result = result.union(other)


city  rank  score1  score2  country  grade
Rome        2.0   0.0     0.0     0.0      0.0    0.0
london      2.0   0.0     0.0     0.0      0.0    0.0
one         0.0   4.0     0.0     0.0      0.0    0.0
rome        1.0   0.0     0.0     0.0      0.0    0.0
sidney      2.0   0.0     0.0     0.0      0.0    0.0
two         0.0   3.0     0.0     0.0      0.0    0.0
20.0        0.0   0.0     1.0     1.0      0.0    0.0
30.0        0.0   0.0     1.0     1.0      0.0    0.0
40.0        0.0   0.0     1.0     1.0      0.0    0.0
66.0        0.0   0.0     1.0     0.0      0.0    0.0
55.0        0.0   0.0     1.0     0.0      0.0    0.0
45.0        0.0   0.0     1.0     0.0      0.0    0.0
22.0        0.0   0.0     1.0     0.0      0.0    0.0
50.0        0.0   0.0     0.0     1.0      0.0    0.0
60.0        0.0   0.0     0.0     1.0      0.0    0.0
70.0        0.0   0.0     0.0     1.0      0.0    0.0
80.0        0.0   0.0     0.0     1.0      0.0    0.0
Kosti       0.0   0.0     0.0     0.0      1.0    0.0
average     0.0   0.0     0.0     0.0      0.0    3.0
good        0.0   0.0     0.0     0.0      0.0    2.0
brilliant   0.0   0.0     0.0     0.0      0.0    1.0
low         0.0   0.0     0.0     0.0      0.0    1.0

In [137]:
#unique values
d['score1'].unique()

array([22., 45., 55., 66., 40., 30., 20., nan])

In [138]:
d

city rank  score1  score2 country      grade
0         rome  one    22.0    80.0     NaN  brilliant
1         Rome  two    45.0    70.0     NaN       good
2       sidney  one    55.0    60.0     NaN       good
3       london  two    66.0    50.0     NaN    average
4       london  one    40.0    40.0     NaN    average
5         Rome  two    30.0    30.0     NaN    average
6       sidney  one    20.0    20.0     NaN        low
madani     NaN  NaN     NaN     NaN   Kosti        NaN

In [53]:
#randomize
b = np.random.permutation(d.shape[0])
b

array([4, 5, 1, 0, 7, 3, 6, 2])

In [54]:
d.take(b) # apply and change the rows

city rank  score1  score2 country      grade
4         rome  one    40.0    40.0     NaN    average
5        sinar  two    30.0    30.0     NaN    average
1        sinar  two    45.0    70.0     NaN       good
0       madani  one    22.0    80.0     NaN  brilliant
madani     NaN  NaN     NaN     NaN   Kosti        NaN
3       london  two    66.0    50.0     NaN    average
6       sidney  one    20.0    20.0     NaN        low
2       sidney  one    55.0    60.0     NaN       good

In [55]:
# we can change the order of the index 
# d.index
d_index = np.random.permutation(d.index)

In [139]:
d_index

array(['madani', 6, 3, 0, 2, 1, 4, 5], dtype=object)

In [140]:
# another way to randomize we can use sample
d.sample(n =7)

city rank  score1  score2 country      grade
2       sidney  one    55.0    60.0     NaN       good
0         rome  one    22.0    80.0     NaN  brilliant
madani     NaN  NaN     NaN     NaN   Kosti        NaN
3       london  two    66.0    50.0     NaN    average
6       sidney  one    20.0    20.0     NaN        low
4       london  one    40.0    40.0     NaN    average
5         Rome  two    30.0    30.0     NaN    average

In [142]:
# to randomize a certain col 
s = d['country']
len(s)
r_enteries = np.random.permutation(len(s))
d['country'] = s[r_enteries].values # then we can pass it to the col

In [143]:
r_enteries

array([2, 7, 6, 1, 0, 3, 5, 4])

In [144]:
#using sys we can get the size of elemnt etc in byt
liste =  [1,2,3,5,6]
sys.getsizeof(liste)
# one int take 28 of byte 

104

In [158]:
# to know the memeory locaton we use (id)
x = 300
y = 300
print(id(x))
print(id(y))
print(x is y)

2472508890736
2472508890928
False
